version: "3.8"

services:
  news-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-collector
    ports:
      - "2112:2112"
    environment:
      - APP_ENV=production
      - KAFKA_DRY_RUN=false
      - KAFKA_BROKERS=kafka:29092
    networks:
      - kafka_default
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - news-collector
    networks:
      - kafka_default
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Admin dashboard access password
    depends_on:
      - prometheus
    networks:
      - kafka_default
    restart: unless-stopped

networks:
  kafka_default:
    external: true
